import { all_routes } from "../../../feature-module/routes/all_routes";

const routes = all_routes;

export const SidebarData = [
  {
    tittle: "Super Admin",
    icon: "shield-lock",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Dashboard",
        link: routes.superAdminDashboard,
        submenu: false,
        showSubRoute: false,
        icon: "layout-dashboard",
        base: "dashboard",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Enterprise mang.",
        link: routes.tenants,
        submenu: false,
        showSubRoute: false,
        icon: "building-hospital",
        base: "tenants",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Packages",
        link: routes.packages,
        submenu: false,
        showSubRoute: false,
        icon: "package",
        base: "packages",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Demo Bookings",
        link: routes.demoBookings,
        submenu: false,
        showSubRoute: false,
        icon: "calendar-event",
        base: "demo-bookings",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Analytics",
        link: routes.incomeReport,
        submenu: false,
        showSubRoute: false,
        icon: "chart-line",
        base: "reports",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Support",
        link: routes.tickets,
        submenu: false,
        showSubRoute: false,
        icon: "headset",
        base: "support",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Privacy Policy",
        link: routes.privacyPolicyAdmin,
        submenu: false,
        showSubRoute: false,
        icon: "file-text",
        base: "settings",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Terms & Conditions",
        link: routes.termsConditionAdmin,
        submenu: false,
        showSubRoute: false,
        icon: "file-certificate",
        base: "settings",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Refund Policy",
        link: routes.refundPolicyAdmin,
        submenu: false,
        showSubRoute: false,
        icon: "receipt-refund",
        base: "settings",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Contact Settings",
        link: routes.contactSettingsAdmin,
        submenu: false,
        showSubRoute: false,
        icon: "phone",
        base: "settings",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Email Settings",
        link: routes.superAdminEmailSettings,
        submenu: false,
        showSubRoute: false,
        icon: "mail",
        base: "settings",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Razorpay Settings",
        link: routes.superAdminRazorpaySettings,
        submenu: false,
        showSubRoute: false,
        icon: "credit-card",
        base: "settings",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Main Menu",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Dashboard",

        link: routes.dashboard,
        submenu: false,
        showSubRoute: false,
        icon: "layout-dashboard",
        base: "dashboard",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },

    ],
  },
  {
    tittle: "Clinic",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Doctors",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "user-plus",
        base: "Doctors",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Doctors", link: routes.doctors },
          { label: "Add Doctor", link: routes.addDoctors },
          { label: "Doctor Schedule", link: routes.doctorScheduleClini },
        ],
      },
      {
        label: "Patients",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "user-heart",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Patients", link: routes.patients },
          { label: "Create Patient", link: routes.createPatient },
        ],
      },
      {
        label: "Appointments",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "calendar-check",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Appointments", link: routes.appointments },
          { label: "New Appointment", link: routes.newAppointment },
        ],
      },
      {
        label: "Consultations",
        link: routes.consultations,
        submenu: false,
        showSubRoute: false,
        icon: "clipboard-list",
        base: "Consultations",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Services",
        link: routes.services,
        submenu: false,
        showSubRoute: false,
        icon: "map-pin",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },

    ],
  },
  {
    tittle: "Diagnostic",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Dashboard",
        link: routes.pathlabDashboard,
        submenu: false,
        showSubRoute: false,
        icon: "layout-dashboard",
        base: "pathlab",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Category",
        link: routes.pathlabCategories,
        submenu: false,
        showSubRoute: false,
        icon: "tags",
        base: "pathlab",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Diagnostic Test",
        link: routes.pathlabTests,
        submenu: false,
        showSubRoute: false,
        icon: "microscope",
        base: "pathlab",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Diagnostic Booking",
        link: routes.pathlabBookings,
        submenu: false,
        showSubRoute: false,
        icon: "calendar-event",
        base: "pathlab",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Invoice",
        link: routes.pathlabInvoices,
        submenu: false,
        showSubRoute: false,
        icon: "file-invoice",
        base: "pathlab",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Pharmacy",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Dashboard",
        link: routes.pharmacyDashboard,
        submenu: false,
        showSubRoute: false,
        icon: "layout-dashboard",
        base: "pharmacy",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Category",
        link: routes.pharmacyCategories,
        submenu: false,
        showSubRoute: false,
        icon: "tags",
        base: "pharmacy",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Medicine",
        link: routes.pharmacyMedicines,
        submenu: false,
        showSubRoute: false,
        icon: "pill",
        base: "pharmacy",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Inventory",
        link: routes.pharmacyInventory,
        submenu: false,
        showSubRoute: false,
        icon: "package",
        base: "pharmacy",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Pharmacy Billing",
        link: routes.pharmacyBilling,
        submenu: false,
        showSubRoute: false,
        icon: "file-invoice",
        base: "pharmacy",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Sales History",
        link: routes.pharmacySalesHistory,
        submenu: false,
        showSubRoute: false,
        icon: "chart-line",
        base: "pharmacy",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Therapy",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Dashboard",
        link: routes.dashboard,
        submenu: false,
        showSubRoute: false,
        icon: "layout-dashboard",
        base: "dashboard",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Patients",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "user-heart",
        base: "therapy-patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Patient List", link: routes.patients },
          { label: "Register Patient", link: routes.createPatient },
        ],
      },
      {
        label: "Therapists",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "user-check",
        base: "therapy-therapists",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Therapist List", link: routes.therapistList },
          { label: "Add Therapist", link: routes.addTherapist },
        ],
      },
      {
        label: "Therapies",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "stethoscope",
        base: "therapy-services",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Categories", link: routes.therapyCategories },
          { label: "Therapy List", link: routes.therapyServices },
          { label: "Add Therapy", link: routes.addService },
        ],
      },
      {
        label: "Appointments",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "calendar-event",
        base: "therapy-appointments",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Appointment List", link: routes.therapyAppointments },
          { label: "Book Appointment", link: routes.bookTherapyAppointment },
        ],
      },
      {
        label: "Consultancy",
        link: routes.therapyConsultations,
        submenu: false,
        showSubRoute: false,
        icon: "clipboard-list",
        base: "therapy-consultations",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Invoices",
        link: routes.invoices + "?type=therapy",
        submenu: false,
        showSubRoute: false,
        icon: "file-invoice",
        base: "therapy-billing",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Reports",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "report",
        base: "therapy-reports",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Appointment Report", link: routes.therapyAppointmentReport },
          { label: "Session Report", link: routes.therapySessionReport },
          { label: "Therapist Report", link: routes.therapyTherapistReport },
          { label: "Revenue Report", link: routes.therapyRevenueReport },
          { label: "Patient Progress Report", link: routes.patientProgressReport },
        ],
      },
    ],
  },
  {
    tittle: "HRM",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Staffs",
        link: routes.staffs,
        submenu: false,
        showSubRoute: false,
        icon: "users-group",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Departments",
        link: routes.hrmDepartments,
        submenu: false,
        showSubRoute: false,
        icon: "building-bank",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Designation",
        link: routes.designation,
        submenu: false,
        showSubRoute: false,
        icon: "user-cog",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },

      {
        label: "Attendance",
        link: routes.attendance,
        submenu: false,
        showSubRoute: false,
        icon: "user-check",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },

      {
        label: "Leaves",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "users-minus",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Leaves", link: routes.leaves },
          { label: "Leave Type", link: routes.leaveType },
        ],
      },
      {
        label: "Holidays",
        link: routes.holidays,
        submenu: false,
        showSubRoute: false,
        icon: "home-exclamation",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Payroll",
        link: routes.payroll,
        submenu: false,
        showSubRoute: false,
        icon: "coin",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Specializations",
        link: routes.specializations,
        submenu: false,
        showSubRoute: false,
        icon: "user-shield",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Finance & Accounts",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Expenses",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "credit-card",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Expenses", link: routes.expenses },
          { label: "Expense Category", link: routes.expenseCategory },
        ],
      },
      {
        label: "Invoices",
        link: routes.invoices + "?type=clinic",
        submenu: false,
        showSubRoute: false,
        icon: "file-invoice",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Transactions",
        link: routes.transactions,
        submenu: false,
        showSubRoute: false,
        icon: "transition-right",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Content",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Pages",
        link: routes.pages,
        submenu: false,
        showSubRoute: false,
        icon: "brand-pagekit",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Blogs",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "brand-blogger",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Add Blogs",
            link: routes.addBlogs,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Blogs",
            link: routes.blogs,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Blog Categories",
            link: routes.blogCategories,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Blog Comments",
            link: routes.blogComments,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Locations",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "map-pins",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Countries",
            link: routes.countries,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "States",
            link: routes.states,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Cities",
            link: routes.cities,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Testimonials",
        link: routes.testimonials,
        submenu: false,
        showSubRoute: false,
        icon: "brand-wechat",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "FAQ’S",
        link: routes.faq,
        submenu: false,
        showSubRoute: false,
        icon: "question-mark",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },

  {
    tittle: "Authentication",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Login",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "login",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Cover",
            link: routes.loginCover,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Illustration",
            link: routes.loginillustration,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Basic",
            link: routes.loginbasic,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Register",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "file-pencil",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Cover",
            link: routes.registercover,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Illustration",
            link: routes.registerillustration,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Basic",
            link: routes.registerbasic,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Forgot Password",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "lock-exclamation",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Cover",
            link: routes.forgotpasswordcover,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Illustration",
            link: routes.forgotpasswordillustration,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Basic",
            link: routes.forgotpasswordbasic,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Reset Password",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "restore",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Cover",
            link: routes.resetpasswordcover,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Illustration",
            link: routes.resetpasswordillustration,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Basic",
            link: routes.resetpasswordbasic,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Email Verification",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "mail-check",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Cover",
            link: routes.emailverificationcover,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Illustration",
            link: routes.emailverificationillustration,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Basic",
            link: routes.emailverificationbasic,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "2 Step Verification",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "discount-check",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Cover",
            link: routes.twostepverificationcover,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Illustration",
            link: routes.twostepverificationillustration,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Basic",
            link: routes.twostepverificationbasic,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Lock Screen",
        link: routes.lockscreen,
        submenu: false,
        showSubRoute: false,
        icon: "lock",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [],
      },
      {
        label: "Error Pages",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "exclamation-mark-off",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "404 Error",
            link: routes.error404,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "500 Error",
            link: routes.error500,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
    ],
  },
  {
    tittle: "UI Interface",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Base UI",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "chart-pie",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Accordion",
            link: routes.uiAccordion,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Alerts",
            link: routes.uiAlerts,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Avatar",
            link: routes.uiAvatar,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Badges",
            link: routes.uiBadges,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Breadcrumb",
            link: routes.uiBreadcrumb,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Buttons",
            link: routes.uiButtons,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Button Group",
            link: routes.uiButtonsGroup,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Card",
            link: routes.uiCards,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Carousel",
            link: routes.uiCarousel,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Collapse",
            link: routes.uiCollapse,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Dropdowns",
            link: routes.uiDropdowns,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Ratio",
            link: routes.uiRatio,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Grid",
            link: routes.uiGrid,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Images",
            link: routes.uiImages,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Links",
            link: routes.uiLinks,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "List Group",
            link: routes.uiListGroup,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Modals",
            link: routes.uiModals,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Offcanvas",
            link: routes.uiOffcanvas,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Pagination",
            link: routes.uiPagination,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Placeholders",
            link: routes.uiPlaceholders,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Popovers",
            link: routes.uiPopovers,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Progress",
            link: routes.uiProgress,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Scrollspy",
            link: routes.uiScrollspy,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Spinner",
            link: routes.uiSpinner,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Tabs",
            link: routes.uiNavTabs,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Toasts",
            link: routes.uiToasts,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Tooltips",
            link: routes.uiTooltips,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Typography",
            link: routes.uiTypography,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Utilities",
            link: routes.uiUtilities,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Advanced UI",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "radar",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Dragula",
            link: routes.dragula,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Clipboard",
            link: routes.uiClipboard,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Range Slider",
            link: routes.uiRangeslider,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Lightbox",
            link: routes.uiLightbox,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Rating",
            link: routes.uiRating,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Counter",
            link: routes.uiCounter,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Scrollbar",
            link: routes.uiScrollbar,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Forms",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "forms",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Form Elements",
            link: "apps",
            submenu: true,
            showSubRoute: false,
            base: "inventory",
            materialicons: "dashboard",
            submenuItems: [
              {
                label: "Basic Inputs",
                link: routes.formBasicInputs,
                base: "invoices",
                customSubmenuTwo: false,
              },
              {
                label: "Checkbox & Radios",
                link: routes.formCheckboxRadios,
                base: "invoices",
                customSubmenuTwo: false,
              },
              {
                label: "Input Groups",
                link: routes.formInputGroups,
                base: "invoices",
                customSubmenuTwo: false,
              },
              {
                label: "Grid & Gutters",
                link: routes.formGridGutters,
                base: "invoices",
                customSubmenuTwo: false,
              },
              {
                label: "Input Masks",
                link: routes.formMask,
                base: "invoices",
                customSubmenuTwo: false,
              },
              {
                label: "File Uploads",
                link: routes.formFileupload,
                base: "invoices",
                customSubmenuTwo: false,
              },
            ],
          },
          {
            label: "Layouts",
            link: "apps",
            submenu: true,
            showSubRoute: false,
            base: "inventory",
            materialicons: "dashboard",
            submenuItems: [
              {
                label: "Horizontal Form",
                link: routes.formHorizontal,
                base: "invoices",
                customSubmenuTwo: false,
              },
              {
                label: "Vertical Form",
                link: routes.formVertical,
                base: "invoices",
                customSubmenuTwo: false,
              },
              {
                label: "Floating Labels",
                link: routes.formFloatingLabels,
                base: "invoices",
                customSubmenuTwo: false,
              },
            ],
          },
          {
            label: "Form Validation",
            link: routes.formValidation,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Select2",
            link: routes.formSelect2,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Form Wizard",
            link: routes.formWizard,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Form Picker",
            link: routes.formPickers,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Tables",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "table-row",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Basic Tables ",
            link: routes.tablesBasic,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Data Table ",
            link: routes.dataTables,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Charts",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "chart-donut",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Apex Charts",
            link: routes.chartApex,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Icons",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "icons",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Fontawesome Icons",
            link: routes.iconFontawesome,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Tabler Icons",
            link: routes.iconTabler,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Bootstrap Icons",
            link: routes.iconBootstrap,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Remix Icons",
            link: routes.iconRemix,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Ionic Icons",
            link: routes.iconIonic,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Material Icons",
            link: routes.iconMaterial,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Pe7 Icons",
            link: routes.iconPe7,
            base: "invoices",
            customSubmenuTwo: false,
          },

          {
            label: "Themify Icons",
            link: routes.iconThemify,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Weather Icons",
            link: routes.iconWeather,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Typicon Icons",
            link: routes.iconTypicon,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Flag Icons",
            link: routes.iconFlag,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
    ],
  },
  {
    tittle: "Help",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Documentation",
        link: "",
        submenu: false,
        showSubRoute: false,
        icon: "file-dots",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Changelog",
        link: "",
        submenu: false,
        showSubRoute: false,
        icon: "status-change",
        base: "frontent",
        version: "v1.6.7",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Application",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "To Do",
        link: routes.todoList,
        submenu: false,
        showSubRoute: false,
        icon: "calendar-check",
        base: "todo",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Notes",
        link: routes.notes,
        submenu: false,
        showSubRoute: false,
        icon: "file-text",
        base: "notes",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Support",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    hideHeader: true,
    submenuItems: [
      {
        label: "Support",
        link: routes.tickets,
        submenu: false,
        showSubRoute: false,
        icon: "ticket",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Administration",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    hideHeader: true,
    submenuItems: [
      {
        label: "Roles & Permissions",
        link: routes.rolesPermissions,
        submenu: false,
        showSubRoute: false,
        icon: "user-cog",
        base: "users",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
];
