import { all_routes } from "../../../feature-module/routes/all_routes";

const routes = all_routes;

export const SidebarData = [
  {
    tittle: "Super Admin",
    icon: "shield-lock",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Dashboard",
        link: routes.superAdminDashboard,
        submenu: false,
        showSubRoute: false,
        icon: "layout-dashboard",
        base: "dashboard",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Enterprise mang.",
        link: routes.tenants,
        submenu: false,
        showSubRoute: false,
        icon: "building-hospital",
        base: "tenants",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Packages",
        link: routes.packages,
        submenu: false,
        showSubRoute: false,
        icon: "package",
        base: "packages",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Demo Bookings",
        link: routes.demoBookings,
        submenu: false,
        showSubRoute: false,
        icon: "calendar-event",
        base: "demo-bookings",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Analytics",
        link: routes.incomeReport,
        submenu: false,
        showSubRoute: false,
        icon: "chart-line",
        base: "reports",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Support",
        link: routes.tickets,
        submenu: false,
        showSubRoute: false,
        icon: "headset",
        base: "support",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Privacy Policy",
        link: routes.privacyPolicyAdmin,
        submenu: false,
        showSubRoute: false,
        icon: "file-text",
        base: "settings",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Terms & Conditions",
        link: routes.termsConditionAdmin,
        submenu: false,
        showSubRoute: false,
        icon: "file-certificate",
        base: "settings",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Refund Policy",
        link: routes.refundPolicyAdmin,
        submenu: false,
        showSubRoute: false,
        icon: "receipt-refund",
        base: "settings",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Contact Settings",
        link: routes.contactSettingsAdmin,
        submenu: false,
        showSubRoute: false,
        icon: "phone",
        base: "settings",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Email Settings",
        link: routes.superAdminEmailSettings,
        submenu: false,
        showSubRoute: false,
        icon: "mail",
        base: "settings",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Razorpay Settings",
        link: routes.superAdminRazorpaySettings,
        submenu: false,
        showSubRoute: false,
        icon: "credit-card",
        base: "settings",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Main Menu",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    hideHeader: true,
    submenuItems: [
      {
        label: "Dashboard",
        link: routes.aboutDocYori,
        submenu: false,
        showSubRoute: false,
        icon: "layout-dashboard",
        base: "about-docyori",
        materialicons: "start",
        dot: false,
        submenuItems: [],
      },
      {
        label: "OPD",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "stethoscope",
        base: "opd",
        materialicons: "start",
        dot: true,
        submenuItems: [
          {
            label: "Dashboard",
            link: routes.dashboard,
            submenu: false,
            showSubRoute: false,
            icon: "layout-dashboard",
            base: "dashboard",
            submenuItems: [],
          },
          {
            label: "Doctors",
            link: "index",
            submenu: true,
            showSubRoute: false,
            icon: "stethoscope",
            base: "Doctors",
            submenuItems: [
              {
                label: "Doctors",
                link: routes.doctors,
                icon: "user-heart",
                activePrefixes: ["/edit-doctors/", "/doctor-details/"],
              },
              { label: "Add Doctor", link: routes.addDoctors, icon: "user-plus" },
              { label: "Doctor Schedule", link: routes.doctorScheduleClini, icon: "calendar-event" },
            ],
          },
          {
            label: "Patients",
            link: "index",
            submenu: true,
            showSubRoute: false,
            icon: "users",
            base: "Patients",
            submenuItems: [
              { label: "Patients", link: routes.patients, icon: "users" },
              { label: "Create Patient", link: routes.createPatient, icon: "user-plus" },
            ],
          },
          {
            label: "Appointments",
            link: "index",
            submenu: true,
            showSubRoute: false,
            icon: "calendar-check",
            base: "Appointments",
            submenuItems: [
              { label: "Appointments", link: routes.appointments, icon: "calendar-check" },
              { label: "New Appointment", link: routes.newAppointment, icon: "calendar-plus" },
            ],
          },
          {
            label: "Consultations",
            link: routes.consultations,
            submenu: false,
            showSubRoute: false,
            icon: "clipboard-list",
            base: "Consultations",
            submenuItems: [],
          },
        ],
      },
      {
        label: "IPD",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "bed",
        base: "ipd",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Dashboard", link: routes.ipdDashboard, icon: "layout-dashboard" },
          { label: "Patient", link: routes.ipdPatients, icon: "users" },
          { label: "Admission", link: routes.ipdAdmissions, icon: "login" },
          { label: "Inpatient", link: routes.ipdInpatients, icon: "bed" },
          { label: "Discharge", link: routes.ipdDischarge, icon: "logout" },
          { label: "Ward Management", link: routes.ipdWardManagement, icon: "building-hospital" },
          { label: "Billings & Invoices", link: routes.ipdBillings, icon: "file-invoice" },
          { label: "Doctor", link: routes.ipdDoctors, icon: "stethoscope" },
          { label: "Treatment & Packages", link: routes.ipdTreatments, icon: "medical-cross" },
        ],
      },
      {
        label: "Diagnostic",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "microscope",
        base: "diagnostic",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Dashboard", link: routes.pathlabDashboard, icon: "layout-dashboard" },
          { label: "Category", link: routes.pathlabCategories, icon: "category" },
          { label: "Diagnostic Test", link: routes.pathlabTests, icon: "test-pipe" },
          { label: "Diagnostic Booking", link: routes.pathlabBookings, icon: "calendar-check" },
          { label: "Invoice", link: routes.pathlabInvoices, icon: "file-invoice" },
        ],
      },
      {
        label: "Pharmacy",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "pill",
        base: "pharmacy",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Dashboard", link: routes.pharmacyDashboard, icon: "layout-dashboard" },
          { label: "Category", link: routes.pharmacyCategories, icon: "category" },
          { label: "Medicine", link: routes.pharmacyMedicines, icon: "pill" },
          { label: "Inventory", link: routes.pharmacyInventory, icon: "packages" },
          { label: "Pharmacy Billing", link: routes.pharmacyBilling, icon: "receipt" },
          { label: "Sales History", link: routes.pharmacySalesHistory, icon: "history" },
        ],
      },
      {
        label: "HRM",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "users-group",
        base: "hrm",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Staffs", link: routes.staffs, icon: "users" },
          { label: "Departments", link: routes.hrmDepartments, icon: "building" },
          { label: "Designation", link: routes.designation, icon: "id" },
          { label: "Attendance", link: routes.attendance, icon: "user-check" },
          {
            label: "Leaves",
            link: "index",
            submenu: true,
            icon: "calendar-off",
            submenuItems: [
              { label: "Leaves", link: routes.leaves, icon: "calendar-off" },
              { label: "Leave Type", link: routes.leaveType, icon: "list-details" },
            ],
          },
          { label: "Holidays", link: routes.holidays, icon: "beach" },
          { label: "Payroll", link: routes.payroll, icon: "cash" },
        ],
      },
      {
        label: "Finance & Accounts",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "report-money",
        base: "finance",
        materialicons: "start",
        dot: true,
        submenuItems: [
          {
            label: "Expenses",
            link: "index",
            submenu: true,
            icon: "wallet",
            submenuItems: [
              { label: "Expenses", link: routes.expenses, icon: "wallet" },
              { label: "Expense Category", link: routes.expenseCategory, icon: "category" },
            ],
          },
          { label: "Invoices", link: routes.invoices + "?type=clinic", icon: "file-invoice" },
          { label: "Transactions", link: routes.transactions, icon: "arrows-exchange" },
        ],
      },
      {
        label: "Application",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "apps",
        base: "application",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "To Do", link: routes.todoList, icon: "checkbox" },
          { label: "Notes", link: routes.notes, icon: "notes" },
        ],
      },
    ],
  },
  {
    tittle: "Therapy",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Dashboard",
        link: routes.dashboard,
        submenu: false,
        showSubRoute: false,
        icon: "layout-dashboard",
        base: "dashboard",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Patients",
        link: routes.patients,
        submenu: false,
        showSubRoute: false,
        icon: "user-heart",
        base: "therapy-patients",
        materialicons: "start",
        dot: true,
        submenuItems: [],
        activePrefixes: ["/edit-patient/", "/patient-details/", "/create-patient", "/patients-grid"],
      },
      {
        label: "Therapists",
        link: routes.therapistList,
        submenu: false,
        showSubRoute: false,
        icon: "user-check",
        base: "therapy-therapists",
        materialicons: "start",
        dot: true,
        submenuItems: [],
        activePrefixes: ["/edit-doctors/", "/doctor-details/", "/add-therapist"],
      },
      {
        label: "Therapies",
        link: routes.therapyServices,
        submenu: false,
        showSubRoute: false,
        icon: "stethoscope",
        base: "therapy-services",
        materialicons: "start",
        dot: true,
        submenuItems: [],
        activePrefixes: ["/therapy-categories", "/add-service", "/therapy-services"],
      },
      {
        label: "Appointments",
        link: routes.therapyAppointments,
        submenu: false,
        showSubRoute: false,
        icon: "calendar-event",
        base: "therapy-appointments",
        materialicons: "start",
        dot: true,
        submenuItems: [],
        activePrefixes: ["/book-therapy-appointment"],
      },
      {
        label: "Consultancy",
        link: routes.therapyConsultations,
        submenu: false,
        showSubRoute: false,
        icon: "clipboard-list",
        base: "therapy-consultations",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Sessions",
        link: routes.allSessions,
        submenu: false,
        showSubRoute: false,
        icon: "calendar-check",
        base: "all-sessions",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Invoices",
        link: routes.invoices + "?type=therapy",
        submenu: false,
        showSubRoute: false,
        icon: "file-invoice",
        base: "therapy-billing",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Content",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Pages",
        link: routes.pages,
        submenu: false,
        showSubRoute: false,
        icon: "brand-pagekit",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Blogs",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "brand-blogger",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Add Blogs",
            link: routes.addBlogs,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Blogs",
            link: routes.blogs,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Blog Categories",
            link: routes.blogCategories,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Blog Comments",
            link: routes.blogComments,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Locations",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "map-pins",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Countries",
            link: routes.countries,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "States",
            link: routes.states,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Cities",
            link: routes.cities,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Testimonials",
        link: routes.testimonials,
        submenu: false,
        showSubRoute: false,
        icon: "brand-wechat",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "FAQ’S",
        link: routes.faq,
        submenu: false,
        showSubRoute: false,
        icon: "question-mark",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },

  {
    tittle: "Authentication",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Login",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "login",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Cover",
            link: routes.loginCover,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Illustration",
            link: routes.loginillustration,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Basic",
            link: routes.loginbasic,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Register",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "file-pencil",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Cover",
            link: routes.registercover,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Illustration",
            link: routes.registerillustration,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Basic",
            link: routes.registerbasic,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Forgot Password",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "lock-exclamation",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Cover",
            link: routes.forgotpasswordcover,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Illustration",
            link: routes.forgotpasswordillustration,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Basic",
            link: routes.forgotpasswordbasic,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Reset Password",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "restore",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Cover",
            link: routes.resetpasswordcover,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Illustration",
            link: routes.resetpasswordillustration,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Basic",
            link: routes.resetpasswordbasic,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Email Verification",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "mail-check",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Cover",
            link: routes.emailverificationcover,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Illustration",
            link: routes.emailverificationillustration,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Basic",
            link: routes.emailverificationbasic,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "2 Step Verification",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "discount-check",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Cover",
            link: routes.twostepverificationcover,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Illustration",
            link: routes.twostepverificationillustration,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Basic",
            link: routes.twostepverificationbasic,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Lock Screen",
        link: routes.lockscreen,
        submenu: false,
        showSubRoute: false,
        icon: "lock",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [],
      },
      {
        label: "Error Pages",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "exclamation-mark-off",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "404 Error",
            link: routes.error404,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "500 Error",
            link: routes.error500,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
    ],
  },
  {
    tittle: "UI Interface",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Base UI",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "chart-pie",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Accordion",
            link: routes.uiAccordion,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Alerts",
            link: routes.uiAlerts,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Avatar",
            link: routes.uiAvatar,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Badges",
            link: routes.uiBadges,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Breadcrumb",
            link: routes.uiBreadcrumb,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Buttons",
            link: routes.uiButtons,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Button Group",
            link: routes.uiButtonsGroup,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Card",
            link: routes.uiCards,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Carousel",
            link: routes.uiCarousel,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Collapse",
            link: routes.uiCollapse,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Dropdowns",
            link: routes.uiDropdowns,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Ratio",
            link: routes.uiRatio,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Grid",
            link: routes.uiGrid,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Images",
            link: routes.uiImages,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Links",
            link: routes.uiLinks,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "List Group",
            link: routes.uiListGroup,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Modals",
            link: routes.uiModals,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Offcanvas",
            link: routes.uiOffcanvas,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Pagination",
            link: routes.uiPagination,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Placeholders",
            link: routes.uiPlaceholders,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Popovers",
            link: routes.uiPopovers,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Progress",
            link: routes.uiProgress,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Scrollspy",
            link: routes.uiScrollspy,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Spinner",
            link: routes.uiSpinner,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Tabs",
            link: routes.uiNavTabs,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Toasts",
            link: routes.uiToasts,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Tooltips",
            link: routes.uiTooltips,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Typography",
            link: routes.uiTypography,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Utilities",
            link: routes.uiUtilities,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Advanced UI",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "radar",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Dragula",
            link: routes.dragula,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Clipboard",
            link: routes.uiClipboard,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Range Slider",
            link: routes.uiRangeslider,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Lightbox",
            link: routes.uiLightbox,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Rating",
            link: routes.uiRating,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Counter",
            link: routes.uiCounter,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Scrollbar",
            link: routes.uiScrollbar,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Forms",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "forms",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Form Elements",
            link: "apps",
            submenu: true,
            showSubRoute: false,
            base: "inventory",
            materialicons: "dashboard",
            submenuItems: [
              {
                label: "Basic Inputs",
                link: routes.formBasicInputs,
                base: "invoices",
                customSubmenuTwo: false,
              },
              {
                label: "Checkbox & Radios",
                link: routes.formCheckboxRadios,
                base: "invoices",
                customSubmenuTwo: false,
              },
              {
                label: "Input Groups",
                link: routes.formInputGroups,
                base: "invoices",
                customSubmenuTwo: false,
              },
              {
                label: "Grid & Gutters",
                link: routes.formGridGutters,
                base: "invoices",
                customSubmenuTwo: false,
              },
              {
                label: "Input Masks",
                link: routes.formMask,
                base: "invoices",
                customSubmenuTwo: false,
              },
              {
                label: "File Uploads",
                link: routes.formFileupload,
                base: "invoices",
                customSubmenuTwo: false,
              },
            ],
          },
          {
            label: "Layouts",
            link: "apps",
            submenu: true,
            showSubRoute: false,
            base: "inventory",
            materialicons: "dashboard",
            submenuItems: [
              {
                label: "Horizontal Form",
                link: routes.formHorizontal,
                base: "invoices",
                customSubmenuTwo: false,
              },
              {
                label: "Vertical Form",
                link: routes.formVertical,
                base: "invoices",
                customSubmenuTwo: false,
              },
              {
                label: "Floating Labels",
                link: routes.formFloatingLabels,
                base: "invoices",
                customSubmenuTwo: false,
              },
            ],
          },
          {
            label: "Form Validation",
            link: routes.formValidation,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Select2",
            link: routes.formSelect2,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Form Wizard",
            link: routes.formWizard,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Form Picker",
            link: routes.formPickers,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Tables",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "table-row",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Basic Tables ",
            link: routes.tablesBasic,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Data Table ",
            link: routes.dataTables,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Charts",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "chart-donut",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Apex Charts",
            link: routes.chartApex,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Icons",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "icons",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Fontawesome Icons",
            link: routes.iconFontawesome,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Tabler Icons",
            link: routes.iconTabler,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Bootstrap Icons",
            link: routes.iconBootstrap,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Remix Icons",
            link: routes.iconRemix,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Ionic Icons",
            link: routes.iconIonic,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Material Icons",
            link: routes.iconMaterial,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Pe7 Icons",
            link: routes.iconPe7,
            base: "invoices",
            customSubmenuTwo: false,
          },

          {
            label: "Themify Icons",
            link: routes.iconThemify,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Weather Icons",
            link: routes.iconWeather,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Typicon Icons",
            link: routes.iconTypicon,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Flag Icons",
            link: routes.iconFlag,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
    ],
  },
  {
    tittle: "Help",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Documentation",
        link: "",
        submenu: false,
        showSubRoute: false,
        icon: "file-dots",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Changelog",
        link: "",
        submenu: false,
        showSubRoute: false,
        icon: "status-change",
        base: "frontent",
        version: "v1.6.7",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Support",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    hideHeader: true,
    submenuItems: [
      {
        label: "Support",
        link: routes.tickets,
        submenu: false,
        showSubRoute: false,
        icon: "ticket",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Administration",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    hideHeader: true,
    submenuItems: [
      {
        label: "Roles & Permissions",
        link: routes.rolesPermissions,
        submenu: false,
        showSubRoute: false,
        icon: "user-cog",
        base: "users",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Refer Sources",
        link: routes.refers,
        submenu: false,
        showSubRoute: false,
        icon: "user-check",
        base: "refers",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
];
